### ISSUE TITLE
requiring the package.

### ISSUE THREAD

**Issue by Madses** [aalexgabi/node-adwords-es5#1]
var Adwords = require('node-adwords'); Doesn't seem to work. I get the following error: 

```
Error: Cannot find module 'node-adwords'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\kevin\Desktop\adwordsapi\app.js:1:100)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Shouldnt it be var Adwords = require('node-adwords-es5'); It does seem to work when i do that though. Maybe update the documentation.

**Comment by aalexgabi** [comment]
@Madses Thank you for reporting this.

Indeed the module name has not been updated in `readme.md` since the fork. I just published a new version containing the fix: https://github.com/aalexgabi/node-adwords-es5/commit/c04ac8cd4d237358f4d185b93c0488ea5ed63dd8.
